name: constraint_learning 
channels:
    - defaults
    - conda-forge
    - anaconda
    - mosek

dependencies:
    - python=3.10
    - pip=22.3

    - numpy>=1.23.5
    - scipy>=1.9.3
    - seaborn>=0.12.2
    - cvxpy>=1.3.2
    - cvxopt>=1.3.0
    - progressbar2>=4.2.0
    - pytest>=7.2.2
    - jupyter>=1.0.0
    - black>=23.1.0
    - mosek
    - tbb=2020.2 # sparseqr conflict
    - autograd>=1.6.2

    - pip:
      - sparseqr
      - asrl-pylgmath>=1.0.3
      - -e poly_matrix # build local poly_matrix submodule
      - -e .  # build local lifting package
